name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'  # Set the PHP version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get install unzip  # Install unzip if needed
          curl -sS https://getcomposer.org/installer | php  # Install Composer
          mv composer.phar /usr/local/bin/composer  # Move Composer to global bin
          composer install  # Install PHP dependencies

      # Step 4: Run PHPUnit tests (uses phpunit.xml configuration)
      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --configuration phpunit.xml  # Run all tests defined in phpunit.xml
